language: node_js
node_js:
  - "8"
env:
  global:
    secure: fUd88QDsxQ/UKZSfPtSrkIPWTKn33ozBACkPsb1Uya/NSrVF1tiC+jS17GaBoJ0TWlPmtkADU6luisQ7q2CpXHsVSaEcZVVo3ETyihHLxP01h54pybrF4mhjadhWsz7JZ5WVeU6d+zk+G0280EI1wWsQicBTQWMcoYB5QWZeBRo=
install: npm install
script:
  - npx tsc
  - npm test
deploy:
  skip_cleanup: true
  provider: script
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    - npm publish
  on:
    tags: true
    repo: hotchemi/zaim.js
